# Generated by Django 3.0.8 on 2020-11-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedsreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pending_reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
